src/Domain/Course/Entity/Formation.php
<?php

namespace App\Domain\Course\Entity;

use App\Domain\Application\Entity\Content;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 */
class Formation extends Content
{
    use LevelTrait;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private ?string $short = null;

    /**
     * @ORM\Column(type="json")
     *
     * @return array{title: string, courses: int[]}[]
     */
    private array $chapters = [];

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $youtube_playlist = null;

    /**
     * @ORM\OneToMany(targetEntity="App\Domain\Course\Entity\Course", mappedBy="formation")
     *
     * @var Collection<int, Course>
     */
    private $courses;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private ?string $links = null;

    public function __construct()
    {
        $this->courses = new ArrayCollection();
        parent::__construct();
    }

    public function getShort(): ?string
    {
        return $this->short;
    }

    public function setShort(?string $short): self
    {
        $this->short = $short;

        return $this;
    }

    /**
     * Initialise les chapitres depuis le JSON.
     *
     * @return Chapter[]
     */
    public function getChapters(): array
    {
        return Chapter::makeFromFormation($this);
    }

    /**
     * Rempli le champs JSON à partir d'un tableau d'objet chapitres.
     *
     * @var Chapter[]
     */
    public function setChapters(array $chapters): self
    {
        $this->chapters = array_map(function (Chapter $chapter) {
            return [
                'title' => $chapter->getTitle(),
                'courses' => array_map(fn (Course $course) => $course->getId(), $chapter->getCourses()),
            ];
        }, $chapters);

        return $this;
    }

    /**
     * Renvoie les données brut (JSON).
     */
    public function getRawChapters(): array
    {
        return $this->chapters;
    }

    /**
     * @param list<array{title: string, courses: int[]}> $chapters
     */
    public function setRawChapters(array $chapters): self
    {
        $this->chapters = $chapters;

        return $this;
    }

    public function getDuration(): int
    {
        return array_reduce($this->courses->toArray(), function (int $acc, Course $item) {
            $acc += $item->getDuration();

            return $acc;
        }, 0);
    }

    public function getYoutubePlaylist(): ?string
    {
        return $this->youtube_playlist;
    }

    public function setYoutubePlaylist(?string $youtube_playlist): self
    {
        $this->youtube_playlist = $youtube_playlist;

        return $this;
    }

    /**
     * @return Collection<int, Course>
     */
    public function getCourses(): Collection
    {
        return $this->courses;
    }

    public function addCourse(Course $course): self
    {
        if (!$this->courses->contains($course)) {
            $this->courses[] = $course;
            $course->setFormation($this);
        }

        return $this;
    }

    public function removeCourse(Course $course): self
    {
        if ($this->courses->contains($course)) {
            $this->courses->removeElement($course);
            // set the owning side to null (unless already changed)
            if ($course->getFormation() === $this) {
                $course->setFormation(null);
            }
        }

        return $this;
    }

    public function getCoursesById(): array
    {
        $courses = $this->getCourses();
        $coursesById = [];
        foreach ($courses as $course) {
            $coursesById[$course->getId()] = $course;
        }

        return $coursesById;
    }

    public function getLinks(): ?string
    {
        return $this->links;
    }

    public function setLinks(?string $links): self
    {
        $this->links = $links;

        return $this;
    }
}

src/Http/Admin/Controller/FormationController.php
<?php

namespace App\Http\Admin\Controller;

use App\Domain\Application\Event\ContentCreatedEvent;
use App\Domain\Application\Event\ContentDeletedEvent;
use App\Domain\Application\Event\ContentUpdatedEvent;
use App\Domain\Course\Entity\Formation;
use App\Http\Admin\Data\FormationCrudData;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/formation", name="formation_")
 *
 * @method getRepository() App\Domain\Formation\$formation\$formation\Forma
 */
final class FormationController extends CrudController
{
    protected string $templatePath = 'formation';
    protected string $menuItem = 'formation';
    protected string $entity = Formation::class;
    protected string $routePrefix = 'admin_formation';
    protected array $events = [
        'update' => ContentUpdatedEvent::class,
        'delete' => ContentDeletedEvent::class,
        'create' => ContentCreatedEvent::class,
    ];

    /**
     * @Route("/", name="index")
     */
    public function index(): Response
    {
        $this->paginator->allowSort('row.id');
        $query = $this->getRepository()
            ->createQueryBuilder('row')
            ->leftJoin('row.technologyUsages', 'tu')
            ->leftJoin('tu.technology', 't')
            ->addSelect('t', 'tu')
            ->orderby('row.createdAt', 'DESC')
        ;

        return $this->crudIndex($query);
    }

    /**
     * @Route("/new", name="new", methods={"POST", "GET"})
     */
    public function new(): Response
    {
        $entity = (new Formation())->setAuthor($this->getUser());
        $data = new FormationCrudData($entity);

        return $this->crudNew($data);
    }

    /**
     * @Route("/{id}", name="edit", methods={"POST", "GET"})
     */
    public function edit(Formation $formation): Response
    {
        $data = (new FormationCrudData($formation))->setEntityManager($this->em);

        return $this->crudEdit($data);
    }

    /**
     * @Route("/{id}", methods={"DELETE"})
     */
    public function delete(Formation $formation): Response
    {
        return $this->crudDelete($formation);
    }
}

src/Http/Controller/FormationController.php
<?php

namespace App\Http\Controller;

use App\Domain\Course\Entity\Formation;
use App\Domain\Course\Repository\FormationRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class FormationController extends AbstractController
{
    /**
     * @Route("/formations", name="formation_index")
     */
    public function index(FormationRepository $formationRepository): Response
    {
        $formations = $formationRepository->findAll();

        return $this->render('formations/index.html.twig', [
            'formations' => $formations,
        ]);
    }

    /**
     * @Route("/formations/{slug}", name="formation_show")
     */
    public function show(Formation $formation): Response
    {
        return $this->render('formations/show.html.twig', [
            'formation' => $formation,
        ]);
    }
}

templates/formations/_card-large.html.twig
{% cache [formation, 'card'] %}
  <article class="card card--formation">
    <div class="card__body stack">
      <div class="flex-md">

        <h2 class="card__title" style="margin-bottom: 4px;">
          <a href="{{ path('formation_show', {slug: formation.slug}) }}" tabindex="-1">
            {{ formation.title }}
          </a>
        </h2>

        <div class="flex text-muted hstack" style="--gap:1">
          <div>{{ icon('lines') }} {{ formation.courses | length }} Chapitres</div>
          <div>{{ icon('clock') }} {{ formation.duration | duration }}</div>
        </div>

      </div>

      <div class="card__description">
        {{ formation.short }}
      </div>

      <a href="{{ path('formation_show', {slug: formation.slug}) }}" title="{{ formation.title }}"
         class="card__link"></a>
    </div>
  </article>
{% endcache %}

templates/formations/_card.html.twig
{% cache [formation, 'card'] %}
  <article class="card card--formation">
    <div class="card__body stack">
      <div class="card__icons">
        {% for technology in formation.mainTechnologies %}
          <a href="{{ path('technology_show', {slug: technology.slug}) }}" class="course__icon" tabindex="-1">
            <img src="{{ uploads_path('icons/' ~ technology.image) }}" alt="{{ technology.name }}">
          </a>
        {% endfor %}
      </div>

      <h2 class="card__title" style="margin-bottom: 4px;">
        <a href="{{ path('formation_show', {slug: formation.slug}) }}" tabindex="-1">
          {{ formation.title }}
        </a>
      </h2>

      <div class="card__description">
        {{ formation.content | markdown | striptags | excerpt(130) }}
      </div>
      <a href="{{ path('formation_show', {slug: formation.slug}) }}" title="{{ formation.title }}"
         class="card__link"></a>
    </div>
    <footer class="card__footer">
      <div>{{ icon('lines') }} {{ formation.courses | length }} Chapitres</div>
      <div>{{ icon('clock') }} {{ formation.duration | duration }}</div>
    </footer>
  </article>
{% endcache %}

templates/formations/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

  <div class="formations">
    {% for formation in formations %}
      {% include 'formations/_card.html.twig' %}
    {% endfor %}
  </div>

{% endblock %}

templates/formations/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}

  {% cache [formation, 'show'] %}

    <header class="wave-header">
      <div class="wave-header__body stack">
        <h1 class="wave-header__title">{{ formation.title }}</h1>
        <p>{{ formation.short }}</p>
        <p>
          <button class="btn-primary btn-big" style="color: #FFF; border-color:#FFF;">Continuer</button>
        </p>
      </div>
      <div class="wave-header__image">
        <img src="{{ uploads_path('icons/' ~ formation.mainTechnologies[0].image) }}" alt="">
      </div>
      <waves-shape class="waves" position="bottom" target=".wave-header"></waves-shape>
    </header>

    <section class="formation-single">
      <div class="formation-chapters">
        <h2 class="hero-title">Chapitres</h2>
        {% include 'chapters/_summary.html.twig' with {chapters: formation.chapters, class: 'chapters-split'} only %}
      </div>
      <div class="formation-summary">
        <h2 class="hero-title">Présentation</h2>
        <div class="stack" style="--gap:4">
        <div class="formatted">
          {{ formation.content | markdown }}
          <p class="text-muted">
            {{ formation.createdAt | ago }}
          </p>
        </div>
        <div class="formation-arguments">
          <div class="formation-argument">
            <div class="formation-arguments_title">Liens utiles</div>
            {{ formation.links | markdown }}
          </div>
          <div class="formation-argument">
            <div class="formation-arguments_title">Informations</div>
            <ul>
              <li>{{ formation.duration | duration }} de vidéos</li>
              <li>{{ formation.courses.count }} chapitres</li>
            </ul>
          </div>
          <div class="formation-argument">
            <div class="formation-arguments_title">Prérequis</div>
            <ul>
              {% for technology in formation.secondaryTechnologies %}
                <li><a href="{{ path(technology) }}">{{ technology.name }}</a></li>
              {% endfor %}
            </ul>
          </div>
        </div>

        {% set course = formation.chapters[0].courses[0] %}
        <youtube-player
          video="{{ course.youtubeId }}"
          poster="{{ image_url(course.image) }}"
          title="{{ course.title }}"
          button="#chapter{{ course.id }} play-button"
          id="coursePlayer"
          class="shadow"></youtube-player>
        </div>
      </div>
    </section>

  {% endcache %}

  {{ show_history(formation.courses.toArray) }}

{% endblock %}